name: CI

on:
  push:
  pull_request:

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest -q

      - name: Build Docker image
        run: docker build -t devops-starter .

      - name: Lint (basic)
        run: |
          python -m pyflakes app.py || true

      - name: Build Docker image
        run: |
          docker build -t devops-starter .